package application

import (
	"context"
	"fmt"
	"time"

	"jobconnect/services/connects/internal/domain"
)

type UseCases struct {
	repo ConnectsRepository
}

func NewUseCases(repo ConnectsRepository) *UseCases {
	return &UseCases{repo: repo}
}

func (uc *UseCases) GetBalance(ctx context.Context, userID string) (domain.ConnectsBalance, error) {
	return uc.repo.GetBalance(ctx, userID)
}

func (uc *UseCases) DeductConnects(ctx context.Context, userID string, amount int32, refID, refType string) (domain.ConnectsBalance, error) {
	if amount <= 0 {
		return domain.ConnectsBalance{}, domain.ErrNegativeDeduction
	}
	if amount < 1 && refType == string(domain.TxTypeProposalSubmitted) {
		return domain.ConnectsBalance{}, domain.ErrInvalidConnectsMinimum
	}

	tx := domain.ConnectsTransaction{
		UserID:        userID,
		Amount:        -amount, // negative for deduction
		Type:          domain.TransactionType(refType),
		ReferenceID:   refID,
		ReferenceType: refType,
		CreatedAt:     time.Now().UTC(),
	}

	return uc.repo.ExecuteTransaction(ctx, tx)
}

func (uc *UseCases) RefundConnects(ctx context.Context, userID string, amount int32, refID, refType string) (domain.ConnectsBalance, error) {
	if amount <= 0 {
		return domain.ConnectsBalance{}, domain.ErrNegativeDeduction
	}

	tx := domain.ConnectsTransaction{
		UserID:        userID,
		Amount:        amount, // positive for refund
		Type:          domain.TransactionType(refType),
		ReferenceID:   fmt.Sprintf("%s_refund", refID), // Append refund to make unique idempotency key
		ReferenceType: refType,
		CreatedAt:     time.Now().UTC(),
	}

	return uc.repo.ExecuteTransaction(ctx, tx)
}

func (uc *UseCases) GrantInitialConnects(ctx context.Context, userID string) (domain.ConnectsBalance, error) {
	tx := domain.ConnectsTransaction{
		UserID:        userID,
		Amount:        50, // 50 free connects
		Type:          domain.TxTypeRegisterBonus,
		ReferenceID:   fmt.Sprintf("initial_%s", userID),
		ReferenceType: string(domain.TxTypeRegisterBonus),
		CreatedAt:     time.Now().UTC(),
	}

	return uc.repo.ExecuteTransaction(ctx, tx)
}

func (uc *UseCases) PurchaseConnects(ctx context.Context, userID string, amount int32) (domain.ConnectsBalance, error) {
	if amount <= 0 {
		return domain.ConnectsBalance{}, domain.ErrNegativeDeduction
	}

	// NOTE: Real implementation would have an idempotency key generated by the client or payment gateway
	// For MVP, we just use a timestamp based ID to avoid unique constraints violation
	refID := fmt.Sprintf("purchase_%d", time.Now().UnixNano())

	tx := domain.ConnectsTransaction{
		UserID:        userID,
		Amount:        amount,
		Type:          domain.TxTypeFiatPurchase,
		ReferenceID:   refID,
		ReferenceType: string(domain.TxTypeFiatPurchase),
		CreatedAt:     time.Now().UTC(),
	}

	return uc.repo.ExecuteTransaction(ctx, tx)
}
