import type { Metadata } from "next";

import "./globals.css";
import Navbar from "../components/Navbar";
import Footer from "@/components/Footer";
import StoreProvider from "@/store/StoreProvider";





export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" data-theme="light">
      <body
       
      >
        <StoreProvider>
          <Navbar />
          {children}
          <Footer />

        </StoreProvider>
      </body>
    </html>
  );
}
