// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             v6.33.1
// source: connects/v1/connects.proto

package connectsv1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	ConnectsService_GetBalance_FullMethodName           = "/connects.v1.ConnectsService/GetBalance"
	ConnectsService_DeductConnects_FullMethodName       = "/connects.v1.ConnectsService/DeductConnects"
	ConnectsService_RefundConnects_FullMethodName       = "/connects.v1.ConnectsService/RefundConnects"
	ConnectsService_GrantInitialConnects_FullMethodName = "/connects.v1.ConnectsService/GrantInitialConnects"
	ConnectsService_PurchaseConnects_FullMethodName     = "/connects.v1.ConnectsService/PurchaseConnects"
)

// ConnectsServiceClient is the client API for ConnectsService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type ConnectsServiceClient interface {
	// Get the current balance for a user
	GetBalance(ctx context.Context, in *GetBalanceRequest, opts ...grpc.CallOption) (*GetBalanceResponse, error)
	// Deduct connects from a user's balance
	DeductConnects(ctx context.Context, in *DeductConnectsRequest, opts ...grpc.CallOption) (*DeductConnectsResponse, error)
	// Refund connects to a user's balance
	RefundConnects(ctx context.Context, in *RefundConnectsRequest, opts ...grpc.CallOption) (*RefundConnectsResponse, error)
	// Grant the initial register bonus of connects
	GrantInitialConnects(ctx context.Context, in *GrantInitialConnectsRequest, opts ...grpc.CallOption) (*GrantInitialConnectsResponse, error)
	// Purchase connects using fiat wallet
	PurchaseConnects(ctx context.Context, in *PurchaseConnectsRequest, opts ...grpc.CallOption) (*PurchaseConnectsResponse, error)
}

type connectsServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewConnectsServiceClient(cc grpc.ClientConnInterface) ConnectsServiceClient {
	return &connectsServiceClient{cc}
}

func (c *connectsServiceClient) GetBalance(ctx context.Context, in *GetBalanceRequest, opts ...grpc.CallOption) (*GetBalanceResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetBalanceResponse)
	err := c.cc.Invoke(ctx, ConnectsService_GetBalance_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *connectsServiceClient) DeductConnects(ctx context.Context, in *DeductConnectsRequest, opts ...grpc.CallOption) (*DeductConnectsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DeductConnectsResponse)
	err := c.cc.Invoke(ctx, ConnectsService_DeductConnects_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *connectsServiceClient) RefundConnects(ctx context.Context, in *RefundConnectsRequest, opts ...grpc.CallOption) (*RefundConnectsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RefundConnectsResponse)
	err := c.cc.Invoke(ctx, ConnectsService_RefundConnects_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *connectsServiceClient) GrantInitialConnects(ctx context.Context, in *GrantInitialConnectsRequest, opts ...grpc.CallOption) (*GrantInitialConnectsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GrantInitialConnectsResponse)
	err := c.cc.Invoke(ctx, ConnectsService_GrantInitialConnects_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *connectsServiceClient) PurchaseConnects(ctx context.Context, in *PurchaseConnectsRequest, opts ...grpc.CallOption) (*PurchaseConnectsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(PurchaseConnectsResponse)
	err := c.cc.Invoke(ctx, ConnectsService_PurchaseConnects_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ConnectsServiceServer is the server API for ConnectsService service.
// All implementations must embed UnimplementedConnectsServiceServer
// for forward compatibility.
type ConnectsServiceServer interface {
	// Get the current balance for a user
	GetBalance(context.Context, *GetBalanceRequest) (*GetBalanceResponse, error)
	// Deduct connects from a user's balance
	DeductConnects(context.Context, *DeductConnectsRequest) (*DeductConnectsResponse, error)
	// Refund connects to a user's balance
	RefundConnects(context.Context, *RefundConnectsRequest) (*RefundConnectsResponse, error)
	// Grant the initial register bonus of connects
	GrantInitialConnects(context.Context, *GrantInitialConnectsRequest) (*GrantInitialConnectsResponse, error)
	// Purchase connects using fiat wallet
	PurchaseConnects(context.Context, *PurchaseConnectsRequest) (*PurchaseConnectsResponse, error)
	mustEmbedUnimplementedConnectsServiceServer()
}

// UnimplementedConnectsServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedConnectsServiceServer struct{}

func (UnimplementedConnectsServiceServer) GetBalance(context.Context, *GetBalanceRequest) (*GetBalanceResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetBalance not implemented")
}
func (UnimplementedConnectsServiceServer) DeductConnects(context.Context, *DeductConnectsRequest) (*DeductConnectsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method DeductConnects not implemented")
}
func (UnimplementedConnectsServiceServer) RefundConnects(context.Context, *RefundConnectsRequest) (*RefundConnectsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method RefundConnects not implemented")
}
func (UnimplementedConnectsServiceServer) GrantInitialConnects(context.Context, *GrantInitialConnectsRequest) (*GrantInitialConnectsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GrantInitialConnects not implemented")
}
func (UnimplementedConnectsServiceServer) PurchaseConnects(context.Context, *PurchaseConnectsRequest) (*PurchaseConnectsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method PurchaseConnects not implemented")
}
func (UnimplementedConnectsServiceServer) mustEmbedUnimplementedConnectsServiceServer() {}
func (UnimplementedConnectsServiceServer) testEmbeddedByValue()                         {}

// UnsafeConnectsServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ConnectsServiceServer will
// result in compilation errors.
type UnsafeConnectsServiceServer interface {
	mustEmbedUnimplementedConnectsServiceServer()
}

func RegisterConnectsServiceServer(s grpc.ServiceRegistrar, srv ConnectsServiceServer) {
	// If the following call panics, it indicates UnimplementedConnectsServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&ConnectsService_ServiceDesc, srv)
}

func _ConnectsService_GetBalance_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetBalanceRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ConnectsServiceServer).GetBalance(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ConnectsService_GetBalance_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ConnectsServiceServer).GetBalance(ctx, req.(*GetBalanceRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ConnectsService_DeductConnects_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeductConnectsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ConnectsServiceServer).DeductConnects(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ConnectsService_DeductConnects_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ConnectsServiceServer).DeductConnects(ctx, req.(*DeductConnectsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ConnectsService_RefundConnects_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RefundConnectsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ConnectsServiceServer).RefundConnects(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ConnectsService_RefundConnects_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ConnectsServiceServer).RefundConnects(ctx, req.(*RefundConnectsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ConnectsService_GrantInitialConnects_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GrantInitialConnectsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ConnectsServiceServer).GrantInitialConnects(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ConnectsService_GrantInitialConnects_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ConnectsServiceServer).GrantInitialConnects(ctx, req.(*GrantInitialConnectsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ConnectsService_PurchaseConnects_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PurchaseConnectsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ConnectsServiceServer).PurchaseConnects(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ConnectsService_PurchaseConnects_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ConnectsServiceServer).PurchaseConnects(ctx, req.(*PurchaseConnectsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// ConnectsService_ServiceDesc is the grpc.ServiceDesc for ConnectsService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var ConnectsService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "connects.v1.ConnectsService",
	HandlerType: (*ConnectsServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetBalance",
			Handler:    _ConnectsService_GetBalance_Handler,
		},
		{
			MethodName: "DeductConnects",
			Handler:    _ConnectsService_DeductConnects_Handler,
		},
		{
			MethodName: "RefundConnects",
			Handler:    _ConnectsService_RefundConnects_Handler,
		},
		{
			MethodName: "GrantInitialConnects",
			Handler:    _ConnectsService_GrantInitialConnects_Handler,
		},
		{
			MethodName: "PurchaseConnects",
			Handler:    _ConnectsService_PurchaseConnects_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "connects/v1/connects.proto",
}
