// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.1
// source: connects/v1/connects.proto

package connectsv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ConnectsBalance struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Balance       int32                  `protobuf:"varint,2,opt,name=balance,proto3" json:"balance,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ConnectsBalance) Reset() {
	*x = ConnectsBalance{}
	mi := &file_connects_v1_connects_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConnectsBalance) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConnectsBalance) ProtoMessage() {}

func (x *ConnectsBalance) ProtoReflect() protoreflect.Message {
	mi := &file_connects_v1_connects_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConnectsBalance.ProtoReflect.Descriptor instead.
func (*ConnectsBalance) Descriptor() ([]byte, []int) {
	return file_connects_v1_connects_proto_rawDescGZIP(), []int{0}
}

func (x *ConnectsBalance) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *ConnectsBalance) GetBalance() int32 {
	if x != nil {
		return x.Balance
	}
	return 0
}

type ConnectsTransaction struct {
	state                protoimpl.MessageState `protogen:"open.v1"`
	Id                   int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	UserId               string                 `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Amount               int32                  `protobuf:"varint,3,opt,name=amount,proto3" json:"amount,omitempty"`
	Type                 string                 `protobuf:"bytes,4,opt,name=type,proto3" json:"type,omitempty"`
	ReferenceId          string                 `protobuf:"bytes,5,opt,name=reference_id,json=referenceId,proto3" json:"reference_id,omitempty"`
	ReferenceType        string                 `protobuf:"bytes,6,opt,name=reference_type,json=referenceType,proto3" json:"reference_type,omitempty"`
	CreatedAtUnixSeconds int64                  `protobuf:"varint,7,opt,name=created_at_unix_seconds,json=createdAtUnixSeconds,proto3" json:"created_at_unix_seconds,omitempty"`
	unknownFields        protoimpl.UnknownFields
	sizeCache            protoimpl.SizeCache
}

func (x *ConnectsTransaction) Reset() {
	*x = ConnectsTransaction{}
	mi := &file_connects_v1_connects_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConnectsTransaction) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConnectsTransaction) ProtoMessage() {}

func (x *ConnectsTransaction) ProtoReflect() protoreflect.Message {
	mi := &file_connects_v1_connects_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConnectsTransaction.ProtoReflect.Descriptor instead.
func (*ConnectsTransaction) Descriptor() ([]byte, []int) {
	return file_connects_v1_connects_proto_rawDescGZIP(), []int{1}
}

func (x *ConnectsTransaction) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *ConnectsTransaction) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *ConnectsTransaction) GetAmount() int32 {
	if x != nil {
		return x.Amount
	}
	return 0
}

func (x *ConnectsTransaction) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *ConnectsTransaction) GetReferenceId() string {
	if x != nil {
		return x.ReferenceId
	}
	return ""
}

func (x *ConnectsTransaction) GetReferenceType() string {
	if x != nil {
		return x.ReferenceType
	}
	return ""
}

func (x *ConnectsTransaction) GetCreatedAtUnixSeconds() int64 {
	if x != nil {
		return x.CreatedAtUnixSeconds
	}
	return 0
}

type GetBalanceRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetBalanceRequest) Reset() {
	*x = GetBalanceRequest{}
	mi := &file_connects_v1_connects_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetBalanceRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetBalanceRequest) ProtoMessage() {}

func (x *GetBalanceRequest) ProtoReflect() protoreflect.Message {
	mi := &file_connects_v1_connects_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetBalanceRequest.ProtoReflect.Descriptor instead.
func (*GetBalanceRequest) Descriptor() ([]byte, []int) {
	return file_connects_v1_connects_proto_rawDescGZIP(), []int{2}
}

func (x *GetBalanceRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

type GetBalanceResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Balance       int32                  `protobuf:"varint,1,opt,name=balance,proto3" json:"balance,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetBalanceResponse) Reset() {
	*x = GetBalanceResponse{}
	mi := &file_connects_v1_connects_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetBalanceResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetBalanceResponse) ProtoMessage() {}

func (x *GetBalanceResponse) ProtoReflect() protoreflect.Message {
	mi := &file_connects_v1_connects_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetBalanceResponse.ProtoReflect.Descriptor instead.
func (*GetBalanceResponse) Descriptor() ([]byte, []int) {
	return file_connects_v1_connects_proto_rawDescGZIP(), []int{3}
}

func (x *GetBalanceResponse) GetBalance() int32 {
	if x != nil {
		return x.Balance
	}
	return 0
}

type DeductConnectsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Amount        int32                  `protobuf:"varint,2,opt,name=amount,proto3" json:"amount,omitempty"`
	ReferenceId   string                 `protobuf:"bytes,3,opt,name=reference_id,json=referenceId,proto3" json:"reference_id,omitempty"`       // e.g., proposal UUID
	ReferenceType string                 `protobuf:"bytes,4,opt,name=reference_type,json=referenceType,proto3" json:"reference_type,omitempty"` // e.g., "PROPOSAL"
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeductConnectsRequest) Reset() {
	*x = DeductConnectsRequest{}
	mi := &file_connects_v1_connects_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeductConnectsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeductConnectsRequest) ProtoMessage() {}

func (x *DeductConnectsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_connects_v1_connects_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeductConnectsRequest.ProtoReflect.Descriptor instead.
func (*DeductConnectsRequest) Descriptor() ([]byte, []int) {
	return file_connects_v1_connects_proto_rawDescGZIP(), []int{4}
}

func (x *DeductConnectsRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *DeductConnectsRequest) GetAmount() int32 {
	if x != nil {
		return x.Amount
	}
	return 0
}

func (x *DeductConnectsRequest) GetReferenceId() string {
	if x != nil {
		return x.ReferenceId
	}
	return ""
}

func (x *DeductConnectsRequest) GetReferenceType() string {
	if x != nil {
		return x.ReferenceType
	}
	return ""
}

type DeductConnectsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	NewBalance    int32                  `protobuf:"varint,2,opt,name=new_balance,json=newBalance,proto3" json:"new_balance,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeductConnectsResponse) Reset() {
	*x = DeductConnectsResponse{}
	mi := &file_connects_v1_connects_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeductConnectsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeductConnectsResponse) ProtoMessage() {}

func (x *DeductConnectsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_connects_v1_connects_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeductConnectsResponse.ProtoReflect.Descriptor instead.
func (*DeductConnectsResponse) Descriptor() ([]byte, []int) {
	return file_connects_v1_connects_proto_rawDescGZIP(), []int{5}
}

func (x *DeductConnectsResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *DeductConnectsResponse) GetNewBalance() int32 {
	if x != nil {
		return x.NewBalance
	}
	return 0
}

type RefundConnectsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Amount        int32                  `protobuf:"varint,2,opt,name=amount,proto3" json:"amount,omitempty"`
	ReferenceId   string                 `protobuf:"bytes,3,opt,name=reference_id,json=referenceId,proto3" json:"reference_id,omitempty"`       // Must match the reference_id used in DeductConnects
	ReferenceType string                 `protobuf:"bytes,4,opt,name=reference_type,json=referenceType,proto3" json:"reference_type,omitempty"` // Must match the reference_type used in DeductConnects
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RefundConnectsRequest) Reset() {
	*x = RefundConnectsRequest{}
	mi := &file_connects_v1_connects_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RefundConnectsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RefundConnectsRequest) ProtoMessage() {}

func (x *RefundConnectsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_connects_v1_connects_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RefundConnectsRequest.ProtoReflect.Descriptor instead.
func (*RefundConnectsRequest) Descriptor() ([]byte, []int) {
	return file_connects_v1_connects_proto_rawDescGZIP(), []int{6}
}

func (x *RefundConnectsRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *RefundConnectsRequest) GetAmount() int32 {
	if x != nil {
		return x.Amount
	}
	return 0
}

func (x *RefundConnectsRequest) GetReferenceId() string {
	if x != nil {
		return x.ReferenceId
	}
	return ""
}

func (x *RefundConnectsRequest) GetReferenceType() string {
	if x != nil {
		return x.ReferenceType
	}
	return ""
}

type RefundConnectsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	NewBalance    int32                  `protobuf:"varint,2,opt,name=new_balance,json=newBalance,proto3" json:"new_balance,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RefundConnectsResponse) Reset() {
	*x = RefundConnectsResponse{}
	mi := &file_connects_v1_connects_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RefundConnectsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RefundConnectsResponse) ProtoMessage() {}

func (x *RefundConnectsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_connects_v1_connects_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RefundConnectsResponse.ProtoReflect.Descriptor instead.
func (*RefundConnectsResponse) Descriptor() ([]byte, []int) {
	return file_connects_v1_connects_proto_rawDescGZIP(), []int{7}
}

func (x *RefundConnectsResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *RefundConnectsResponse) GetNewBalance() int32 {
	if x != nil {
		return x.NewBalance
	}
	return 0
}

type GrantInitialConnectsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GrantInitialConnectsRequest) Reset() {
	*x = GrantInitialConnectsRequest{}
	mi := &file_connects_v1_connects_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GrantInitialConnectsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GrantInitialConnectsRequest) ProtoMessage() {}

func (x *GrantInitialConnectsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_connects_v1_connects_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GrantInitialConnectsRequest.ProtoReflect.Descriptor instead.
func (*GrantInitialConnectsRequest) Descriptor() ([]byte, []int) {
	return file_connects_v1_connects_proto_rawDescGZIP(), []int{8}
}

func (x *GrantInitialConnectsRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

type GrantInitialConnectsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	NewBalance    int32                  `protobuf:"varint,2,opt,name=new_balance,json=newBalance,proto3" json:"new_balance,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GrantInitialConnectsResponse) Reset() {
	*x = GrantInitialConnectsResponse{}
	mi := &file_connects_v1_connects_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GrantInitialConnectsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GrantInitialConnectsResponse) ProtoMessage() {}

func (x *GrantInitialConnectsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_connects_v1_connects_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GrantInitialConnectsResponse.ProtoReflect.Descriptor instead.
func (*GrantInitialConnectsResponse) Descriptor() ([]byte, []int) {
	return file_connects_v1_connects_proto_rawDescGZIP(), []int{9}
}

func (x *GrantInitialConnectsResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *GrantInitialConnectsResponse) GetNewBalance() int32 {
	if x != nil {
		return x.NewBalance
	}
	return 0
}

type PurchaseConnectsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Amount        int32                  `protobuf:"varint,2,opt,name=amount,proto3" json:"amount,omitempty"` // Number of connects to purchase
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PurchaseConnectsRequest) Reset() {
	*x = PurchaseConnectsRequest{}
	mi := &file_connects_v1_connects_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PurchaseConnectsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PurchaseConnectsRequest) ProtoMessage() {}

func (x *PurchaseConnectsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_connects_v1_connects_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PurchaseConnectsRequest.ProtoReflect.Descriptor instead.
func (*PurchaseConnectsRequest) Descriptor() ([]byte, []int) {
	return file_connects_v1_connects_proto_rawDescGZIP(), []int{10}
}

func (x *PurchaseConnectsRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *PurchaseConnectsRequest) GetAmount() int32 {
	if x != nil {
		return x.Amount
	}
	return 0
}

type PurchaseConnectsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	NewBalance    int32                  `protobuf:"varint,2,opt,name=new_balance,json=newBalance,proto3" json:"new_balance,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PurchaseConnectsResponse) Reset() {
	*x = PurchaseConnectsResponse{}
	mi := &file_connects_v1_connects_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PurchaseConnectsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PurchaseConnectsResponse) ProtoMessage() {}

func (x *PurchaseConnectsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_connects_v1_connects_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PurchaseConnectsResponse.ProtoReflect.Descriptor instead.
func (*PurchaseConnectsResponse) Descriptor() ([]byte, []int) {
	return file_connects_v1_connects_proto_rawDescGZIP(), []int{11}
}

func (x *PurchaseConnectsResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *PurchaseConnectsResponse) GetNewBalance() int32 {
	if x != nil {
		return x.NewBalance
	}
	return 0
}

var File_connects_v1_connects_proto protoreflect.FileDescriptor

const file_connects_v1_connects_proto_rawDesc = "" +
	"\n" +
	"\x1aconnects/v1/connects.proto\x12\vconnects.v1\"D\n" +
	"\x0fConnectsBalance\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12\x18\n" +
	"\abalance\x18\x02 \x01(\x05R\abalance\"\xeb\x01\n" +
	"\x13ConnectsTransaction\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\tR\x06userId\x12\x16\n" +
	"\x06amount\x18\x03 \x01(\x05R\x06amount\x12\x12\n" +
	"\x04type\x18\x04 \x01(\tR\x04type\x12!\n" +
	"\freference_id\x18\x05 \x01(\tR\vreferenceId\x12%\n" +
	"\x0ereference_type\x18\x06 \x01(\tR\rreferenceType\x125\n" +
	"\x17created_at_unix_seconds\x18\a \x01(\x03R\x14createdAtUnixSeconds\",\n" +
	"\x11GetBalanceRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\".\n" +
	"\x12GetBalanceResponse\x12\x18\n" +
	"\abalance\x18\x01 \x01(\x05R\abalance\"\x92\x01\n" +
	"\x15DeductConnectsRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12\x16\n" +
	"\x06amount\x18\x02 \x01(\x05R\x06amount\x12!\n" +
	"\freference_id\x18\x03 \x01(\tR\vreferenceId\x12%\n" +
	"\x0ereference_type\x18\x04 \x01(\tR\rreferenceType\"S\n" +
	"\x16DeductConnectsResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x1f\n" +
	"\vnew_balance\x18\x02 \x01(\x05R\n" +
	"newBalance\"\x92\x01\n" +
	"\x15RefundConnectsRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12\x16\n" +
	"\x06amount\x18\x02 \x01(\x05R\x06amount\x12!\n" +
	"\freference_id\x18\x03 \x01(\tR\vreferenceId\x12%\n" +
	"\x0ereference_type\x18\x04 \x01(\tR\rreferenceType\"S\n" +
	"\x16RefundConnectsResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x1f\n" +
	"\vnew_balance\x18\x02 \x01(\x05R\n" +
	"newBalance\"6\n" +
	"\x1bGrantInitialConnectsRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\"Y\n" +
	"\x1cGrantInitialConnectsResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x1f\n" +
	"\vnew_balance\x18\x02 \x01(\x05R\n" +
	"newBalance\"J\n" +
	"\x17PurchaseConnectsRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12\x16\n" +
	"\x06amount\x18\x02 \x01(\x05R\x06amount\"U\n" +
	"\x18PurchaseConnectsResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x1f\n" +
	"\vnew_balance\x18\x02 \x01(\x05R\n" +
	"newBalance2\xee\x03\n" +
	"\x0fConnectsService\x12O\n" +
	"\n" +
	"GetBalance\x12\x1e.connects.v1.GetBalanceRequest\x1a\x1f.connects.v1.GetBalanceResponse\"\x00\x12[\n" +
	"\x0eDeductConnects\x12\".connects.v1.DeductConnectsRequest\x1a#.connects.v1.DeductConnectsResponse\"\x00\x12[\n" +
	"\x0eRefundConnects\x12\".connects.v1.RefundConnectsRequest\x1a#.connects.v1.RefundConnectsResponse\"\x00\x12m\n" +
	"\x14GrantInitialConnects\x12(.connects.v1.GrantInitialConnectsRequest\x1a).connects.v1.GrantInitialConnectsResponse\"\x00\x12a\n" +
	"\x10PurchaseConnects\x12$.connects.v1.PurchaseConnectsRequest\x1a%.connects.v1.PurchaseConnectsResponse\"\x00B-Z+jobconnect/api/proto/connects/v1;connectsv1b\x06proto3"

var (
	file_connects_v1_connects_proto_rawDescOnce sync.Once
	file_connects_v1_connects_proto_rawDescData []byte
)

func file_connects_v1_connects_proto_rawDescGZIP() []byte {
	file_connects_v1_connects_proto_rawDescOnce.Do(func() {
		file_connects_v1_connects_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_connects_v1_connects_proto_rawDesc), len(file_connects_v1_connects_proto_rawDesc)))
	})
	return file_connects_v1_connects_proto_rawDescData
}

var file_connects_v1_connects_proto_msgTypes = make([]protoimpl.MessageInfo, 12)
var file_connects_v1_connects_proto_goTypes = []any{
	(*ConnectsBalance)(nil),              // 0: connects.v1.ConnectsBalance
	(*ConnectsTransaction)(nil),          // 1: connects.v1.ConnectsTransaction
	(*GetBalanceRequest)(nil),            // 2: connects.v1.GetBalanceRequest
	(*GetBalanceResponse)(nil),           // 3: connects.v1.GetBalanceResponse
	(*DeductConnectsRequest)(nil),        // 4: connects.v1.DeductConnectsRequest
	(*DeductConnectsResponse)(nil),       // 5: connects.v1.DeductConnectsResponse
	(*RefundConnectsRequest)(nil),        // 6: connects.v1.RefundConnectsRequest
	(*RefundConnectsResponse)(nil),       // 7: connects.v1.RefundConnectsResponse
	(*GrantInitialConnectsRequest)(nil),  // 8: connects.v1.GrantInitialConnectsRequest
	(*GrantInitialConnectsResponse)(nil), // 9: connects.v1.GrantInitialConnectsResponse
	(*PurchaseConnectsRequest)(nil),      // 10: connects.v1.PurchaseConnectsRequest
	(*PurchaseConnectsResponse)(nil),     // 11: connects.v1.PurchaseConnectsResponse
}
var file_connects_v1_connects_proto_depIdxs = []int32{
	2,  // 0: connects.v1.ConnectsService.GetBalance:input_type -> connects.v1.GetBalanceRequest
	4,  // 1: connects.v1.ConnectsService.DeductConnects:input_type -> connects.v1.DeductConnectsRequest
	6,  // 2: connects.v1.ConnectsService.RefundConnects:input_type -> connects.v1.RefundConnectsRequest
	8,  // 3: connects.v1.ConnectsService.GrantInitialConnects:input_type -> connects.v1.GrantInitialConnectsRequest
	10, // 4: connects.v1.ConnectsService.PurchaseConnects:input_type -> connects.v1.PurchaseConnectsRequest
	3,  // 5: connects.v1.ConnectsService.GetBalance:output_type -> connects.v1.GetBalanceResponse
	5,  // 6: connects.v1.ConnectsService.DeductConnects:output_type -> connects.v1.DeductConnectsResponse
	7,  // 7: connects.v1.ConnectsService.RefundConnects:output_type -> connects.v1.RefundConnectsResponse
	9,  // 8: connects.v1.ConnectsService.GrantInitialConnects:output_type -> connects.v1.GrantInitialConnectsResponse
	11, // 9: connects.v1.ConnectsService.PurchaseConnects:output_type -> connects.v1.PurchaseConnectsResponse
	5,  // [5:10] is the sub-list for method output_type
	0,  // [0:5] is the sub-list for method input_type
	0,  // [0:0] is the sub-list for extension type_name
	0,  // [0:0] is the sub-list for extension extendee
	0,  // [0:0] is the sub-list for field type_name
}

func init() { file_connects_v1_connects_proto_init() }
func file_connects_v1_connects_proto_init() {
	if File_connects_v1_connects_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_connects_v1_connects_proto_rawDesc), len(file_connects_v1_connects_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   12,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_connects_v1_connects_proto_goTypes,
		DependencyIndexes: file_connects_v1_connects_proto_depIdxs,
		MessageInfos:      file_connects_v1_connects_proto_msgTypes,
	}.Build()
	File_connects_v1_connects_proto = out.File
	file_connects_v1_connects_proto_goTypes = nil
	file_connects_v1_connects_proto_depIdxs = nil
}
