// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             v6.33.1
// source: proposal/v1/proposal.proto

package proposalv1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	ProposalService_SubmitProposal_FullMethodName     = "/proposal.v1.ProposalService/SubmitProposal"
	ProposalService_ModifyProposal_FullMethodName     = "/proposal.v1.ProposalService/ModifyProposal"
	ProposalService_WithdrawProposal_FullMethodName   = "/proposal.v1.ProposalService/WithdrawProposal"
	ProposalService_GetProposal_FullMethodName        = "/proposal.v1.ProposalService/GetProposal"
	ProposalService_ListProposalsByJob_FullMethodName = "/proposal.v1.ProposalService/ListProposalsByJob"
	ProposalService_ListMyProposals_FullMethodName    = "/proposal.v1.ProposalService/ListMyProposals"
	ProposalService_SetProposalStatus_FullMethodName  = "/proposal.v1.ProposalService/SetProposalStatus"
)

// ProposalServiceClient is the client API for ProposalService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type ProposalServiceClient interface {
	SubmitProposal(ctx context.Context, in *SubmitProposalRequest, opts ...grpc.CallOption) (*SubmitProposalResponse, error)
	ModifyProposal(ctx context.Context, in *ModifyProposalRequest, opts ...grpc.CallOption) (*ModifyProposalResponse, error)
	WithdrawProposal(ctx context.Context, in *WithdrawProposalRequest, opts ...grpc.CallOption) (*WithdrawProposalResponse, error)
	GetProposal(ctx context.Context, in *GetProposalRequest, opts ...grpc.CallOption) (*GetProposalResponse, error)
	ListProposalsByJob(ctx context.Context, in *ListProposalsByJobRequest, opts ...grpc.CallOption) (*ListProposalsByJobResponse, error)
	ListMyProposals(ctx context.Context, in *ListMyProposalsRequest, opts ...grpc.CallOption) (*ListMyProposalsResponse, error)
	SetProposalStatus(ctx context.Context, in *SetProposalStatusRequest, opts ...grpc.CallOption) (*SetProposalStatusResponse, error)
}

type proposalServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewProposalServiceClient(cc grpc.ClientConnInterface) ProposalServiceClient {
	return &proposalServiceClient{cc}
}

func (c *proposalServiceClient) SubmitProposal(ctx context.Context, in *SubmitProposalRequest, opts ...grpc.CallOption) (*SubmitProposalResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SubmitProposalResponse)
	err := c.cc.Invoke(ctx, ProposalService_SubmitProposal_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *proposalServiceClient) ModifyProposal(ctx context.Context, in *ModifyProposalRequest, opts ...grpc.CallOption) (*ModifyProposalResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ModifyProposalResponse)
	err := c.cc.Invoke(ctx, ProposalService_ModifyProposal_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *proposalServiceClient) WithdrawProposal(ctx context.Context, in *WithdrawProposalRequest, opts ...grpc.CallOption) (*WithdrawProposalResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(WithdrawProposalResponse)
	err := c.cc.Invoke(ctx, ProposalService_WithdrawProposal_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *proposalServiceClient) GetProposal(ctx context.Context, in *GetProposalRequest, opts ...grpc.CallOption) (*GetProposalResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetProposalResponse)
	err := c.cc.Invoke(ctx, ProposalService_GetProposal_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *proposalServiceClient) ListProposalsByJob(ctx context.Context, in *ListProposalsByJobRequest, opts ...grpc.CallOption) (*ListProposalsByJobResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListProposalsByJobResponse)
	err := c.cc.Invoke(ctx, ProposalService_ListProposalsByJob_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *proposalServiceClient) ListMyProposals(ctx context.Context, in *ListMyProposalsRequest, opts ...grpc.CallOption) (*ListMyProposalsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListMyProposalsResponse)
	err := c.cc.Invoke(ctx, ProposalService_ListMyProposals_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *proposalServiceClient) SetProposalStatus(ctx context.Context, in *SetProposalStatusRequest, opts ...grpc.CallOption) (*SetProposalStatusResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SetProposalStatusResponse)
	err := c.cc.Invoke(ctx, ProposalService_SetProposalStatus_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ProposalServiceServer is the server API for ProposalService service.
// All implementations must embed UnimplementedProposalServiceServer
// for forward compatibility.
type ProposalServiceServer interface {
	SubmitProposal(context.Context, *SubmitProposalRequest) (*SubmitProposalResponse, error)
	ModifyProposal(context.Context, *ModifyProposalRequest) (*ModifyProposalResponse, error)
	WithdrawProposal(context.Context, *WithdrawProposalRequest) (*WithdrawProposalResponse, error)
	GetProposal(context.Context, *GetProposalRequest) (*GetProposalResponse, error)
	ListProposalsByJob(context.Context, *ListProposalsByJobRequest) (*ListProposalsByJobResponse, error)
	ListMyProposals(context.Context, *ListMyProposalsRequest) (*ListMyProposalsResponse, error)
	SetProposalStatus(context.Context, *SetProposalStatusRequest) (*SetProposalStatusResponse, error)
	mustEmbedUnimplementedProposalServiceServer()
}

// UnimplementedProposalServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedProposalServiceServer struct{}

func (UnimplementedProposalServiceServer) SubmitProposal(context.Context, *SubmitProposalRequest) (*SubmitProposalResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method SubmitProposal not implemented")
}
func (UnimplementedProposalServiceServer) ModifyProposal(context.Context, *ModifyProposalRequest) (*ModifyProposalResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ModifyProposal not implemented")
}
func (UnimplementedProposalServiceServer) WithdrawProposal(context.Context, *WithdrawProposalRequest) (*WithdrawProposalResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method WithdrawProposal not implemented")
}
func (UnimplementedProposalServiceServer) GetProposal(context.Context, *GetProposalRequest) (*GetProposalResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetProposal not implemented")
}
func (UnimplementedProposalServiceServer) ListProposalsByJob(context.Context, *ListProposalsByJobRequest) (*ListProposalsByJobResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListProposalsByJob not implemented")
}
func (UnimplementedProposalServiceServer) ListMyProposals(context.Context, *ListMyProposalsRequest) (*ListMyProposalsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListMyProposals not implemented")
}
func (UnimplementedProposalServiceServer) SetProposalStatus(context.Context, *SetProposalStatusRequest) (*SetProposalStatusResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method SetProposalStatus not implemented")
}
func (UnimplementedProposalServiceServer) mustEmbedUnimplementedProposalServiceServer() {}
func (UnimplementedProposalServiceServer) testEmbeddedByValue()                         {}

// UnsafeProposalServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ProposalServiceServer will
// result in compilation errors.
type UnsafeProposalServiceServer interface {
	mustEmbedUnimplementedProposalServiceServer()
}

func RegisterProposalServiceServer(s grpc.ServiceRegistrar, srv ProposalServiceServer) {
	// If the following call panics, it indicates UnimplementedProposalServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&ProposalService_ServiceDesc, srv)
}

func _ProposalService_SubmitProposal_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SubmitProposalRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProposalServiceServer).SubmitProposal(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ProposalService_SubmitProposal_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProposalServiceServer).SubmitProposal(ctx, req.(*SubmitProposalRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ProposalService_ModifyProposal_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ModifyProposalRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProposalServiceServer).ModifyProposal(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ProposalService_ModifyProposal_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProposalServiceServer).ModifyProposal(ctx, req.(*ModifyProposalRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ProposalService_WithdrawProposal_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(WithdrawProposalRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProposalServiceServer).WithdrawProposal(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ProposalService_WithdrawProposal_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProposalServiceServer).WithdrawProposal(ctx, req.(*WithdrawProposalRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ProposalService_GetProposal_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetProposalRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProposalServiceServer).GetProposal(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ProposalService_GetProposal_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProposalServiceServer).GetProposal(ctx, req.(*GetProposalRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ProposalService_ListProposalsByJob_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListProposalsByJobRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProposalServiceServer).ListProposalsByJob(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ProposalService_ListProposalsByJob_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProposalServiceServer).ListProposalsByJob(ctx, req.(*ListProposalsByJobRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ProposalService_ListMyProposals_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListMyProposalsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProposalServiceServer).ListMyProposals(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ProposalService_ListMyProposals_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProposalServiceServer).ListMyProposals(ctx, req.(*ListMyProposalsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ProposalService_SetProposalStatus_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SetProposalStatusRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProposalServiceServer).SetProposalStatus(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ProposalService_SetProposalStatus_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProposalServiceServer).SetProposalStatus(ctx, req.(*SetProposalStatusRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// ProposalService_ServiceDesc is the grpc.ServiceDesc for ProposalService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var ProposalService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "proposal.v1.ProposalService",
	HandlerType: (*ProposalServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "SubmitProposal",
			Handler:    _ProposalService_SubmitProposal_Handler,
		},
		{
			MethodName: "ModifyProposal",
			Handler:    _ProposalService_ModifyProposal_Handler,
		},
		{
			MethodName: "WithdrawProposal",
			Handler:    _ProposalService_WithdrawProposal_Handler,
		},
		{
			MethodName: "GetProposal",
			Handler:    _ProposalService_GetProposal_Handler,
		},
		{
			MethodName: "ListProposalsByJob",
			Handler:    _ProposalService_ListProposalsByJob_Handler,
		},
		{
			MethodName: "ListMyProposals",
			Handler:    _ProposalService_ListMyProposals_Handler,
		},
		{
			MethodName: "SetProposalStatus",
			Handler:    _ProposalService_SetProposalStatus_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proposal/v1/proposal.proto",
}
